name: Node.js CI

env:
  CI: true
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: development
  PORT: 3000
  REACT_APP_API_AUTH: http://auth:3001"

on:
  pull_request:
    branches: [develop]

  pull_request_review:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - uses: actions/checkout@v2
      - name: Test Cypress
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      #- run: cp .env.example .env
      - run: docker-compose up -d
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          install: false
          record: true
          parallel: true
          browser: chrome
          headless: true
          group: "Ubuntu18.04 Chrome"
          # start: docker-compose up -d
          wait-on: http://localhost:3000
